pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/srikanth773/demo-page'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('user-page') {
                    sh 'docker build -t user-page .'
                }
            }
        }

        stage('Run Container') {
            steps {
                dir('user-page') {
                    sh '''
                        docker run -d -p 8080:80 user-page
                    '''
                }
            }
        }
    }
}
