pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = 'github-token'  // ✅ ID from Jenkins credentials
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/srikanth773/demo-page',
                    credentialsId: "${GITHUB_CREDENTIALS}"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t user-page .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8080:80 user-page'
            }
        }
    }
}
